name: gpc_frontend
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter_localizations:
      sdk: flutter
    shared_preferences: ^0.5.8
    flutter_bloc: ^6.0.1
    equatable: ^1.2.3
    fluttertoast: ^7.1.1
    cupertino_icons: ^0.1.3
    flutter_spinkit: "^4.1.2"

    # Added for https://flutter.dev/docs/cookbook/networking/send-data
    http: ^0.12.1

    # https://github.com/google/json_serializable.dart/tree/master/example
    # json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://github.com/google/json_serializable.dart/tree/master/example
  # build_runner: ^1.0.0
  # json_serializable: ^3.2.0

flutter:
  uses-material-design: true
